const {test}=require('node:test'),assert=require('node:assert/strict');
const {selectCandidates}=require('./briefing-selection');
const {assertBatch,prepareBatch,readBatch,prefix}=require('./daily-briefing');
const {renderEmailHtml}=require('./send-briefing-mail');
const date='2026-09-12';
const titles=['Accessibilita digitale: nuovi obblighi per i portali','Pensioni di inabilita: aggiornamento della norma','Autismo e progetto di vita: servizi per le famiglie','Cooperative sociali: lavoro e diritti contrattuali','Domotica assistiva: ausili per abitare in autonomia','Bando nazionale welfare e caregiver','Disabilita: nuove misure europee'];
const candidates=titles.map((t,i)=>({titolo_editoriale:t,fonte:'Fonte '+i,url_fonte:'https://example.org/'+i,data_fonte:'2026-09-11',sintesi_editoriale:t}));
const records=n=>Array.from({length:n},(_,i)=>({id:'recTEST'+i,createdTime:date+'T07:00:00Z',fields:{id:prefix(date)+i,stato:'da_valutare',url_fonte:'https://example.org/'+i,titolo_editoriale:'Titolo '+i}}));
test('selection bounded to five',()=>assert.equal(selectCandidates(candidates,[],[],date).selected.length,5));
test('existing URL and Maurizio excluded',()=>{const r=selectCandidates(candidates,[candidates[0]],[{url_articolo:candidates[1].url_fonte}],date);assert(!r.selected.some(x=>[candidates[0].url_fonte,candidates[1].url_fonte].includes(x.url_fonte)));});
test('stale, future, local and marginal excluded',()=>{const bad=[{...candidates[0],data_fonte:'2025-01-01'},{...candidates[1],data_fonte:'2026-09-13'},{...candidates[2],titolo_editoriale:'Festival locale della disabilita'},{...candidates[3],titolo_editoriale:'La festa della musica',sintesi_editoriale:'Concerto in piazza'}];assert.equal(selectCandidates(bad,[],[],date).selected.length,0);});
test('URL tracking and duplicate stories excluded',()=>{const c=candidates[0];assert.equal(selectCandidates([c,{...c,url_fonte:c.url_fonte+'?utm_source=mail'},{...c,url_fonte:'https://elsewhere.org/copy'}],[],[],date).selected.length,1);});
test('hard mail and batch limits reject six',()=>{assert.throws(()=>renderEmailHtml(records(6),'',''));assert.throws(()=>assertBatch(records(6),date));});
test('old or unmarked or published records blocked',()=>{for(const change of [{createdTime:'2026-09-11T08:00:00Z'},{fields:{...records(1)[0].fields,id:'legacy'}},{fields:{...records(1)[0].fields,stato:'pubblicata'}}])assert.throws(()=>assertBatch([{...records(1)[0],...change}],date));});
test('renderer includes exactly five record IDs',()=>{const rs=records(5),html=renderEmailHtml(rs,'','');assert.equal((html.match(/data-airtable-id=/g)||[]).length,5);for(const r of rs)assert(html.includes('data-airtable-id="'+r.id+'"'));});
test('record readback failure blocks briefing',async()=>{await assert.rejects(readBatch(async()=>{throw Error('HTTP 403')},['recTEST0'],date));});
test('real prepare only POST Notizie then GET every newly created ID; rerun no POST',async()=>{let stored=[],posts=0;const calls=[];const api=async(endpoint,method='GET',body)=>{calls.push([endpoint,method]);if(endpoint.startsWith('tblStce'))return {records:[]};if(method==='POST'){posts++;stored=body.records.map((r,i)=>({id:'recNEW'+i,createdTime:date+'T08:00:00Z',fields:r.fields}));return {records:stored};}if(endpoint.includes('?'))return {records:stored};return stored.find(r=>endpoint.endsWith('/'+r.id));};const first=await prepareBatch({api,candidates,date});assert.equal(first.records.length,5);assert.equal(posts,1);assert.equal(calls.filter(([p,m])=>m==='GET'&&p.includes('/recNEW')).length,5);const second=await prepareBatch({api,candidates,date});assert(second.reused);assert.equal(posts,1);assert(calls.filter(([,m])=>m!=='GET').every(([p])=>p==='tblonsfQ2mnaelCAn'));});
test('workflow preview has no Resend secret, no push trigger',()=>{const fs=require('fs'),s=fs.readFileSync('.github/workflows/daily-briefing-mail.yml','utf8');assert(!s.includes('  push:'));const step=s.slice(s.indexOf('      - name: Batch reale'),s.indexOf('      - name: Selezione quotidiana'));assert(!step.includes('RESEND_API_KEY'));assert(step.includes('--preview'));});
const diversityTitles=['Disabilità: trasporti ferroviari e stazioni','Disabilità: comunicazione aumentativa nelle biblioteche','Disabilità: sport acquatici adattati','Disabilità: turismo montano senza barriere','Disabilità: percorsi universitari personalizzati','Disabilità: strumenti finanziari familiari'];
const diversityCandidates=diversityTitles.map((t,i)=>({titolo_editoriale:t,sintesi_editoriale:t,fonte:i===5?'Testata B':'Testata A',url_fonte:'https://example.org/diversity/'+i,data_fonte:'2026-09-11'}));
test('equal relevance favors underrepresented source without exceeding five',()=>{const result=selectCandidates(diversityCandidates,[],[],date);assert.equal(result.selected.length,5);assert.equal(result.selected[1].fonte,'Testata B');});
test('diversity never displaces a higher relevance item',()=>{const items=diversityCandidates.map(x=>({...x}));items[5].titolo_editoriale='Strumenti finanziari familiari';items[5].sintesi_editoriale='Disabilità';const result=selectCandidates(items,[],[],date);assert.equal(result.selected.length,5);assert(result.selected.every(x=>x.fonte==='Testata A'));});
test('single source remains eligible and selection is input-order independent',()=>{const single=diversityCandidates.map(x=>({...x,fonte:'Unica fonte'}));assert.equal(selectCandidates(single,[],[],date).selected.length,5);assert.deepEqual(selectCandidates(diversityCandidates,[],[],date).selected,selectCandidates([...diversityCandidates].reverse(),[],[],date).selected);});
test('one through five new records reach Resend; empty batch never calls Resend',async()=>{
 const fs=require('fs'),os=require('os'),path=require('path');const mail=require('./send-briefing-mail');const today=mail.getIsoDateRome();const dir=fs.mkdtempSync(path.join(os.tmpdir(),'briefing-test-'));const oldFetch=global.fetch,oldKey=process.env.RESEND_API_KEY;let calls=0;
 try{process.env.RESEND_API_KEY='test-only';global.fetch=async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');assert.equal(options.method,'POST');calls++;return new Response(JSON.stringify({id:'test-message-'+calls}),{status:200,headers:{'content-type':'application/json'}});};
 for(let n=0;n<=5;n++){const rs=records(n).map(r=>({...r,createdTime:new Date().toISOString(),fields:{...r.fields,id:prefix(today)+r.id}}));const before=calls;const result=await mail.main({api:async endpoint=>rs.find(r=>endpoint.endsWith('/'+r.id)),batch:{date:today,records:rs},outputDir:dir,dispatchLogPath:path.join(dir,'log-'+n+'.json')});assert.equal(calls-before,n?1:0);if(n)assert.equal(result.httpStatus,200);else assert.equal(result.reason,'no_new_relevant_news');}
 }finally{global.fetch=oldFetch;if(oldKey===undefined)delete process.env.RESEND_API_KEY;else process.env.RESEND_API_KEY=oldKey;fs.rmSync(dir,{recursive:true,force:true});}
});
